name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testing
          POSTGRES_HOST: postgres
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2

      - name: Setup flux authentication
        run: composer config http-basic.composer.fluxui.dev ${{ secrets.FLUX_EMAIL }} ${{ secrets.FLUX_KEY }}

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3

      - name: Install npm packages
        uses: bahmutov/npm-install@v1

      - name: Build vite assets
        run: npm run build
        env:
          VITE_INCLUDE_JQUERY: false

      - name: Setup application key and database
        run: |
          cp .env-ci .env
          php artisan migrate --env=testing
          php artisan key:generate --env=testing

      - name: Run tests
        run: php artisan test --parallel
