name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tournament-test
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      - name: Generate application key
        run: |
          cp .env-ci .env
          php artisan key:generate --env=testing

      - name: Run tests
        run: php artisan test
